# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushDate', models.DateTimeField()),
                ('indexName', models.CharField(help_text='指数名', max_length=8)),
                ('spe', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dpe', models.DecimalField(decimal_places=6, max_digits=10)),
                ('pb', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dp', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
