# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexOverview',
            fields=[
                ('pushDate', models.DateTimeField(primary_key=True, serialize=False)),
                ('spe', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dpe', models.DecimalField(decimal_places=6, max_digits=10)),
                ('pb', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dp', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
