# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csindex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushDate', models.DateTimeField()),
                ('indexName', models.CharField(help_text='指数名', max_length=8)),
                ('closeValue', models.DecimalField(decimal_places=4, max_digits=16)),
                ('delta', models.DecimalField(decimal_places=4, max_digits=16)),
                ('deltaPercent', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
    ]
