# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorSituation',
            fields=[
                ('push_date', models.DateField(help_text='发布时间', primary_key=True, serialize=False)),
                ('new_investor', models.DecimalField(decimal_places=4, help_text='新增投资者数量', max_digits=16)),
                ('new_natural_person', models.DecimalField(decimal_places=4, help_text='新增自然人投资者数量', max_digits=16)),
                ('new_non_natural_person', models.DecimalField(decimal_places=4, help_text='新增非自然人投资者数量', max_digits=16)),
                ('final_investor', models.DecimalField(decimal_places=4, help_text='期末投资者数量', max_digits=16)),
                ('final_natural_person', models.DecimalField(decimal_places=4, help_text='期末自然人投资者数量', max_digits=16)),
                ('final_non_natural_person', models.DecimalField(decimal_places=4, help_text='期末非自然人投资者数量', max_digits=16)),
            ],
        ),
    ]
