# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shiborrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndexInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_date', models.DateField(help_text='发布时间')),
                ('index_name', models.CharField(help_text='指数名', max_length=16)),
                ('open_value', models.DecimalField(decimal_places=4, default=0, help_text='开盘', max_digits=16)),
                ('close_value', models.DecimalField(decimal_places=4, default=0, help_text='收盘', max_digits=16)),
                ('higest_value', models.DecimalField(decimal_places=4, default=0, help_text='最高', max_digits=16)),
                ('lowest_value', models.DecimalField(decimal_places=4, default=0, help_text='最低', max_digits=16)),
                ('spe', models.DecimalField(decimal_places=4, default=0, help_text='静态市盈率', max_digits=16)),
                ('dpe', models.DecimalField(decimal_places=4, default=0, help_text='动态市盈率', max_digits=16)),
                ('pb', models.DecimalField(decimal_places=4, default=0, help_text='市净率', max_digits=16)),
                ('dp', models.DecimalField(decimal_places=4, default=0, help_text='股息率', max_digits=16)),
                ('lyspe', models.DecimalField(decimal_places=4, default=0, help_text='去年底静态市盈率', max_digits=16)),
                ('lydpe', models.DecimalField(decimal_places=4, default=0, help_text='去年底动态市盈率', max_digits=16)),
                ('lypb', models.DecimalField(decimal_places=4, default=0, help_text='去年底市净率', max_digits=16)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockindexinfo',
            unique_together=set([('push_date', 'index_name')]),
        ),
    ]
