# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20170908_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindexinfo',
            name='fluctuation',
            field=models.DecimalField(decimal_places=4, default=0, help_text='涨跌幅', max_digits=16),
        ),
        migrations.AddField(
            model_name='stockindexinfo',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='成交金额', max_digits=16),
        ),
    ]
