# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20170908_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockIndexInfo',
            new_name='StockIndex',
        ),
    ]
