# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20170909_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindex',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='成交金额', max_digits=20),
        ),
    ]
