# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20170909_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindex',
            name='circulation_market_value',
            field=models.DecimalField(decimal_places=4, default=0, help_text='流通市值', max_digits=20),
        ),
        migrations.AddField(
            model_name='stockindex',
            name='total_market_value',
            field=models.DecimalField(decimal_places=4, default=0, help_text='总市值', max_digits=20),
        ),
    ]
