# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20170911_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_code', models.CharField(db_index=True, default='', help_text='基金号码', max_length=16)),
                ('found_name', models.CharField(db_index=True, default='', help_text='基金名称', max_length=32)),
                ('found_manager_user', models.CharField(db_index=True, default='', help_text='基金经理名', max_length=32)),
                ('found_manager_company', models.CharField(db_index=True, default='', help_text='基金管理公司', max_length=32)),
                ('found_type', models.CharField(db_index=True, default='', help_text='基金类型', max_length=32)),
                ('found_birth', models.DateField(db_index=True, default='1000-01-01', help_text='基金成立日期', max_length=32)),
                ('found_exchange', models.CharField(default='', help_text='交易所', max_length=16)),
            ],
        ),
    ]
