# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='公司名')),
                ('stockCode', models.IntegerField()),
                ('partition', models.CharField(max_length=8, verbose_name='版块 ->中小企业板|创业板 ...')),
                ('mainPage', models.CharField(max_length=128, verbose_name='公司在cninfo中的主页地址')),
            ],
        ),
    ]
