# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0002_auto_20170719_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='stockCode',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
