# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0003_auto_20170719_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyInfo',
            new_name='Company',
        ),
    ]
