# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0004_auto_20170720_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='briefName',
            field=models.CharField(default='', help_text='公司简称', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='enlishName',
            field=models.CharField(default='', help_text='英文名称', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='fullName',
            field=models.CharField(default='', help_text='公司全称', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(default='', help_text='行业种类', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='legalPerson',
            field=models.CharField(default='', help_text='法定代表人', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='registeredAddress',
            field=models.CharField(default='', help_text='注册地址', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='registeredCapital',
            field=models.DecimalField(decimal_places=4, default=0, help_text='注册资本', max_digits=16),
        ),
        migrations.AddField(
            model_name='company',
            name='secretaries',
            field=models.CharField(default='', help_text='董秘', max_length=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='mainPage',
            field=models.CharField(help_text='公司在cninfo中的主页地址', max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='公司名', max_length=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='partition',
            field=models.CharField(help_text='版块 中小企业板|创业板 ...', max_length=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='stockCode',
            field=models.CharField(help_text='证券代码', max_length=6, primary_key=True, serialize=False),
        ),
    ]
