# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0006_auto_20170721_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='partition',
            new_name='section',
        ),
    ]
