# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0008_auto_20170723_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registeredAddress',
            field=models.CharField(default='', help_text='注册地址', max_length=64),
        ),
    ]
