# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0011_auto_20170729_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='briefName',
            field=models.CharField(default='', help_text='公司简称', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyFax',
            field=models.CharField(default='', help_text='公司传真', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyPhone',
            field=models.CharField(default='', help_text='公司电话', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyWebsite',
            field=models.CharField(default='', help_text='公司网址', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='fullName',
            field=models.CharField(default='', help_text='公司全称', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 10, 55, 20, 833368), help_text='招股时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legalPerson',
            field=models.CharField(default='', help_text='法定代表人', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='公司名', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='registeredCapital',
            field=models.DecimalField(decimal_places=4, default=0, help_text='注册资本', max_digits=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='secretaries',
            field=models.CharField(default='', help_text='董秘', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='section',
            field=models.CharField(help_text='版块 中小企业板|创业板 ...', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='sponsor',
            field=models.CharField(default='', help_text='保荐机构', max_length=32),
        ),
    ]
