# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0012_auto_20170730_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='briefName',
            field=models.CharField(default='', help_text='公司简称', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyFax',
            field=models.CharField(default='', help_text='公司传真', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyPhone',
            field=models.CharField(default='', help_text='公司电话', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyWebsite',
            field=models.CharField(default='', help_text='公司网址', max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='fullName',
            field=models.CharField(default='', help_text='公司全称', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='ipoPERate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='发行市盈率', max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='issueMode',
            field=models.CharField(default='', help_text='发行方式', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='issuePrice',
            field=models.DecimalField(decimal_places=4, default=0, help_text='发行价格', max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='issueRecommender',
            field=models.CharField(default='', help_text='上市推荐人', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='issuedQuantity',
            field=models.DecimalField(decimal_places=0, default=0, help_text='发行数量', max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 11, 51, 58, 38512), help_text='招股时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='leadUnderwrite',
            field=models.CharField(default='', help_text='主承销商', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='legalPerson',
            field=models.CharField(default='', help_text='法定代表人', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='postalCode',
            field=models.CharField(default='', help_text='邮政编码', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='secretaries',
            field=models.CharField(default='', help_text='董秘', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='sponsor',
            field=models.CharField(default='', help_text='保荐机构', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='stockCode',
            field=models.CharField(help_text='证券代码', max_length=32, primary_key=True, serialize=False),
        ),
    ]
