# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cninfo', '0013_auto_20170801_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enlishName',
            field=models.CharField(default='', help_text='英文名称', max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 11, 55, 53, 780279), help_text='招股时间'),
        ),
    ]
