# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlodPrice',
            fields=[
                ('pushDate', models.DateTimeField(primary_key=True, serialize=False)),
                ('contract', models.CharField(max_length=8)),
                ('openingPrice', models.DecimalField(decimal_places=6, max_digits=10)),
                ('closingPrice', models.DecimalField(decimal_places=6, max_digits=10)),
                ('highestPrice', models.DecimalField(decimal_places=6, max_digits=10)),
                ('minimumPrice', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
