# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOverview',
            fields=[
                ('totalValue', models.DecimalField(decimal_places=4, default=0, help_text='A股总市值', max_digits=16)),
                ('circulationValue', models.DecimalField(decimal_places=4, default=0, help_text='流通市值', max_digits=16)),
                ('tradValue', models.DecimalField(decimal_places=4, default=0, help_text='成交金额', max_digits=16)),
                ('turnoverRate', models.DecimalField(decimal_places=4, default=0, help_text='换手率', max_digits=16)),
                ('PERate', models.DecimalField(decimal_places=4, default=0, help_text='平均市盈率', max_digits=16)),
                ('pushDate', models.DateTimeField(help_text='发布时间', primary_key=True, serialize=False)),
            ],
        ),
    ]
